language: python
python:
  - "3.5"
services:
  - docker
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: Tests
      script: make test
    - stage: Build & Push
      script: make push
env:
  global:
    - DOCKER_USERNAME: tiemenwaterreus
    secure: aClU1N5xm1JRwogLY/1bpmwwbtAohxeI6xKmkqrbXyRt2Sd1bDKaxE+Kw0Hc5nAFR+ks88fES1ODHArqWboc+hQy1p+xoyOIjk4Qxrs5jLhiBHnJBULnuiumXKYEcieEezDnXUWdouSs/OTVckWozCDyEm2L1Aa3TrjZoZ5mBAAueOx/j88agi42T1JDpNV1dG0bI+IXU3QB3gh9hLwM5ziD6s1hYImh1sdav0ISewmbU732/k0BbGmkdqIDx9uw36uQwlELZg/QO5NQ/YjSPvIElMg4Jt65jKuVaRa0dTnhlBnUJ0t+r09m/+5a/qm/kcCk4p5/AP8yaTmPf08vUj3aInpjr1hqnOrHO3GUObuuaY3xK+dN6oP5i/68MXd9yRoc9PfCmWABNaCizSNzpRgABW1EBSzNDGmjDIJBmlCNnbfcwoZSLNXmygARYLUJ2ct0ek/mAhGTNMGjRdQFthsAqFbxxMw57pG5TfmuRv++wk5payklRXYG/0633j9jgn1w2VqLCLp57vJuPuXp5NN5bM5Qu53zddVPUpVOfOmdpr2TVMFyjYoY3Fb7RWTIFCuKXZLam8eQ13qLm7VSCh6+Z0amewCBd8XERRVHY0H4O9hNl7HSD53vb/ntN65QfrTbfFSRMtDl2HRjG2PrtF03r92MUz3xVtmmOANLAaU=
