language: python
python:
  - "3.5"
services:
  - docker
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: Tests
      script: make test
    - stage: Build & Push
      script: make build
      script: make push
